services:
  web_server:
    image: webdevops/php-apache:8.2-alpine
    ports:
      - ${WEB_SERVER_PORT}:80
    working_dir: /app
    container_name: videowall-webserver
    volumes:
      - ./wall:/app

